services:
    Bugloos\ErrorResponseBundle\Normalizer\FormExceptionNormalizer:
        tags: [ 'serializer.normalizer' ]
        arguments:
          [ '@parameter_bag' ]

    Bugloos\ErrorResponseBundle\Normalizer\ErrorResponseNormalizer:
        public: true
        tags: [ 'serializer.normalizer' ]
        arguments:
          [ '@parameter_bag' ]

